/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/skateboard.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/skateboard.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.skateboard_1.geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/skateboard.glb')
