/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bowl-corner-outer.glb --transform --types 
Files: bowl-corner-outer.glb [14.02KB] > /Users/sentional/Desktop/fried-watermelon-chicken-drums-with-pineapple-pizza/public/models/skatepark/bowl-corner-outer-transformed.glb [4.19KB] (70%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['bowl-corner-outer_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/skatepark-transformed/bowl-corner-outer-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['bowl-corner-outer_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models/skatepark-transformed/bowl-corner-outer-transformed.glb')
