/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 half-pipe.glb --transform --types 
Files: half-pipe.glb [5.27KB] > /Users/sentional/Desktop/fried-watermelon-chicken-drums-with-pineapple-pizza/public/models/skatepark/half-pipe-transformed.glb [3.7KB] (30%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['half-pipe_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/skatepark-transformed/half-pipe-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['half-pipe_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models/skatepark-transformed/half-pipe-transformed.glb')
