/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rail-high.glb --transform --types 
Files: rail-high.glb [9.64KB] > /Users/sentional/Desktop/fried-watermelon-chicken-drums-with-pineapple-pizza/public/models/skatepark/rail-high-transformed.glb [3.94KB] (59%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['rail-high_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/skatepark-transformed/rail-high-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['rail-high_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models/skatepark-transformed/rail-high-transformed.glb')
