/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 structure-wood.glb --transform --types 
Files: structure-wood.glb [20.48KB] > /Users/sentional/Desktop/fried-watermelon-chicken-drums-with-pineapple-pizza/public/models/skatepark/structure-wood-transformed.glb [4.34KB] (79%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['structure-wood_1']: THREE.Mesh
  }
  materials: {
    colormap: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/skatepark-transformed/structure-wood-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['structure-wood_1'].geometry} material={materials.colormap} />
    </group>
  )
}

useGLTF.preload('/models/skatepark-transformed/structure-wood-transformed.glb')
