/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 character-skate-boy.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/character-skate-boy.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="character-skate-boy">
        <group name="character-skate-boy_1">
          <primitive object={nodes.root} />
          <skinnedMesh name="body-mesh" geometry={nodes['body-mesh'].geometry} material={materials.colormap} skeleton={nodes['body-mesh'].skeleton} />
          <skinnedMesh name="head-mesh" geometry={nodes['head-mesh'].geometry} material={materials.colormap} skeleton={nodes['head-mesh'].skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/character-skate-boy.glb')
